query ($owner: String! $name: String! $number: Int!) { repository(name: $name owner: $owner) { pullRequest (number: $number) { reviewThreads(first: 15) { edges { node { id originalLine comments(first: 15) { edges { node { id author{login} body publishedAt createdAt} } } } } } reviews (first: 15) { edges { node { id state comments (first: 15) {edges {node {id body replyTo{id}}}} author {login} body publishedAt submittedAt } } } comments(first: 15){ edges { node{ author {login} body } } } } } }
