[package]
name = "ghterm"
version = "0.1.0"
authors = ["Sergey Pikhota <sergey@pikhota.com>"]
edition = "2018"

[dependencies]
termion = "1"
json = "0.12.4"
chrono = "0.4"
args = "2.0"
getopts = "0.2.21"
xdg = "^2.1"
if_chain = "1.0.2"
